# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.srcs/sources_1/ip/fir_rrc_rx/fir_rrc_rx.xci
# IP: The module: 'fir_rrc_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.gen/sources_1/ip/fir_rrc_rx/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_rrc_rx'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.gen/sources_1/ip/fir_rrc_rx/fir_rrc_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_rrc_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.srcs/sources_1/ip/fir_rrc_rx/fir_rrc_rx.xci
# IP: The module: 'fir_rrc_rx' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.gen/sources_1/ip/fir_rrc_rx/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_rrc_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hong/workspace_modem/single_carrier_modem/single_carrier_modem.gen/sources_1/ip/fir_rrc_rx/fir_rrc_rx_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_rrc_rx'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
