#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Mar 17 14:24:08 KST 2026
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail

# resolve compiled library path in xsim.ini
export RDI_DATADIR="/home/hong/tools/Xilinx/Vivado/2024.2/data"

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_14 -L axi_utils_v2_0_10 -L fir_compiler_v7_2_23 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_qpsk_frame_sync_top_behav xil_defaultlib.tb_qpsk_frame_sync_top xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L xbip_utils_v3_0_14 -L axi_utils_v2_0_10 -L fir_compiler_v7_2_23 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_qpsk_frame_sync_top_behav xil_defaultlib.tb_qpsk_frame_sync_top xil_defaultlib.glbl -log elaborate.log

