#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Mar 17 14:24:11 KST 2026
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_qpsk_frame_sync_top_behav -key {Behavioral:sim_1:Functional:tb_qpsk_frame_sync_top} -tclbatch tb_qpsk_frame_sync_top.tcl -view /home/hong/workspace_m10/single_carrier_modem/tb_qpsk_frame_sync_top_behav.wcfg -log simulate.log"
xsim tb_qpsk_frame_sync_top_behav -key {Behavioral:sim_1:Functional:tb_qpsk_frame_sync_top} -tclbatch tb_qpsk_frame_sync_top.tcl -view /home/hong/workspace_m10/single_carrier_modem/tb_qpsk_frame_sync_top_behav.wcfg -log simulate.log

